trigger:
- master

pool:
  testpool1

variables:
  - name: githubToken
    value: $(GITHUB_TOKEN)  # Replace with the actual variable name

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy Django App'

  env:
    PYPI_TOKEN: $(githubToken)  # Use the GitHub token as an environment variable

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      sudo apt-get install python3-venv
	  python -m venv venv
      source venv/bin/activate
      python -m pip install --upgrade pip
	  pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    displayName: 'Setup and install dependencies'

  - script: |
      nohup python manage.py runserver &
      sleep 10
    displayName: 'Run Django Application'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        curl --retry 10 --retry-delay 10 --retry-max-time 60 -v http://localhost:8000
    displayName: 'Verify Application is Running'
