trigger:
- master  # Set the branch you want to trigger the pipeline on

pool:
  testpool1

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy Django App'
  
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'  # Specify the Python version you're using
      addToPath: true

  - script: |
      sudo apt-get install python3-venv
      python3 -m venv venv
      source venv/bin/activate  # For Linux/macOS
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    displayName: 'Setup and install dependencies'

  - script: |
      nohup python manage.py runserver &
      sleep 10  # Allow the server to start before moving on
    displayName: 'Run Django Application'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        curl --retry 10 --retry-delay 10 --retry-max-time 60 -v http://localhost:8000  # Replace 8000 with your actual port
    displayName: 'Verify Application is Running'
